/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjmsmodandr.client;

/**
 *
 * @author kuka
 */
public class Connexion extends javax.swing.JFrame {

    /**
     * Creates new form Connexion
     */
    public Connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_voirHistorique = new javax.swing.JButton();
        B_DiffuserMessage = new javax.swing.JButton();
        B_Rechercher = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        B_Déconnexion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Affichage_Tweet = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_voirHistorique.setText("Voir Historique");
        B_voirHistorique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_voirHistoriqueMouseClicked(evt);
            }
        });

        B_DiffuserMessage.setText("Diffuser message");
        B_DiffuserMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DiffuserMessageActionPerformed(evt);
            }
        });

        B_Rechercher.setText("Rechercher");
        B_Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RechercherActionPerformed(evt);
            }
        });

        jButton4.setLabel("Désabonner");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        B_Déconnexion.setText("Déconnexion");
        B_Déconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_DéconnexionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_DéconnexionMouseEntered(evt);
            }
        });

        Affichage_Tweet.setColumns(20);
        Affichage_Tweet.setRows(5);
        jScrollPane2.setViewportView(Affichage_Tweet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_DiffuserMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_voirHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Déconnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_voirHistorique)
                        .addGap(26, 26, 26)
                        .addComponent(B_DiffuserMessage)
                        .addGap(18, 18, 18)
                        .addComponent(B_Rechercher)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(B_Déconnexion)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RechercherActionPerformed
final Rechercher frame = new Rechercher();
frame.setDefaultCloseOperation(Rechercher.EXIT_ON_CLOSE);
frame.setSize(400, 400);
frame.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_B_RechercherActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void B_DéconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_DéconnexionMouseClicked
  final Acceuil frame = new Acceuil();
frame.setDefaultCloseOperation(Inscription.EXIT_ON_CLOSE);
frame.setSize(400, 400);
frame.setVisible(true);
this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_B_DéconnexionMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void B_voirHistoriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_voirHistoriqueMouseClicked
final VoirHistorique frame = new VoirHistorique();
frame.setDefaultCloseOperation(VoirHistorique.EXIT_ON_CLOSE);
frame.setSize(400, 400);
frame.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_B_voirHistoriqueMouseClicked

    private void B_DéconnexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_DéconnexionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_DéconnexionMouseEntered

    private void B_DiffuserMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiffuserMessageActionPerformed
final DiffuserMessage frame = new DiffuserMessage();
frame.setDefaultCloseOperation(DiffuserMessage.EXIT_ON_CLOSE);
frame.setSize(400, 400);
frame.setVisible(true);
this.dispose();  }       // TODO ad    }//GEN-LAST:event_B_DiffuserMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Affichage_Tweet;
    private javax.swing.JButton B_DiffuserMessage;
    private javax.swing.JButton B_Déconnexion;
    private javax.swing.JButton B_Rechercher;
    private javax.swing.JButton B_voirHistorique;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
